"""Per-paper Microsoft GraphRAG lifecycle: scaffold, build, status, engine cache.

Each paper gets its own GraphRAG root at ``data/<paper_id>/graphrag/``. This module:
  * scaffolds the root (settings.yaml generated from this app's config + GraphRAG
    prompts copied from the bundled graphrag_template/),
  * dumps the corpus from paper.json,
  * builds the index in-process (blocking) or in a background thread,
  * tracks a small status.json the UI can poll (idle|building|ready|failed),
  * lazily constructs and caches one GraphRAGQA engine per paper.

Builds are heavy (minutes, many LLM calls). serve.py kicks one off in the background
when a paper without a healthy index becomes current; whole-paper chat degrades to the
old vector RAG until the index is ready.
"""
from __future__ import annotations

import json
import sys
import threading
import time
from pathlib import Path
from typing import Any

import config

# Parquets that must all exist for an index to count as "built".
_REQUIRED = ("entities", "communities", "community_reports", "text_units", "relationships")

# state machine: idle -> building -> ready | failed
_STATUS_FILE = "status.json"

# Per-paper engine cache + per-paper build lock (so we never build the same root twice).
_engines: dict[str, Any] = {}
_locks: dict[str, threading.Lock] = {}
_locks_guard = threading.Lock()


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

def root_for(paper_id: str) -> Path:
    return config.DATA_DIR / paper_id / "graphrag"


def _lock_for(paper_id: str) -> threading.Lock:
    with _locks_guard:
        return _locks.setdefault(paper_id, threading.Lock())


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def _write_status(root: Path, state: str, message: str = "") -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / _STATUS_FILE).write_text(
        json.dumps({"state": state, "message": message, "updated_at": time.time()}),
        encoding="utf-8",
    )


def read_status(paper_id: str) -> dict[str, Any]:
    """UI-facing status. A live build wins; otherwise reconcile with parquet health."""
    root = root_for(paper_id)
    # An in-progress (possibly forced) rebuild takes precedence over stale parquets.
    if _lock_for(paper_id).locked():
        return {"state": "building", "message": "Rebuilding…"}
    if health(paper_id):
        return {"state": "ready", "message": ""}
    f = root / _STATUS_FILE
    if f.exists():
        try:
            return json.loads(f.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            pass
    return {"state": "idle", "message": ""}


def health(paper_id: str) -> bool:
    """True if all required index output parquets exist."""
    out = root_for(paper_id) / "output"
    return all((out / f"{n}.parquet").exists() for n in _REQUIRED)


# ---------------------------------------------------------------------------
# Scaffolding
# ---------------------------------------------------------------------------

def _settings_yaml() -> str:
    """Generate settings.yaml from this app's config (models, key, optional api_base)."""
    chat_base = (f"\n    api_base: {config.LLM_BASE_URL}" if config.LLM_BASE_URL else "")
    embed_base = (f"\n    api_base: {config.EMBEDDING_BASE_URL}" if config.EMBEDDING_BASE_URL else "")
    return f"""\
### Generated by graphrag_manager from this app's config. Edit graphrag_manager._settings_yaml
### (or env.txt) rather than hand-editing per-paper copies.

completion_models:
  default_completion_model:
    model_provider: openai
    model: {config.GRAPHRAG_CHAT_MODEL}
    auth_method: api_key
    api_key: ${{GRAPHRAG_API_KEY}}{chat_base}
    retry:
      type: exponential_backoff

embedding_models:
  default_embedding_model:
    model_provider: openai
    model: {config.GRAPHRAG_EMBED_MODEL}
    auth_method: api_key
    api_key: ${{GRAPHRAG_API_KEY}}{embed_base}
    retry:
      type: exponential_backoff

input:
  type: text

chunking:
  type: tokens
  size: 1200
  overlap: 100
  encoding_model: o200k_base

input_storage:
  type: file
  base_dir: "input"

output_storage:
  type: file
  base_dir: "output"

reporting:
  type: file
  base_dir: "logs"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

vector_store:
  type: lancedb
  db_uri: output\\lancedb

embed_text:
  embedding_model_id: default_embedding_model

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [concept,method,technique,framework,system,architecture,model,tool,application,dataset,metric,organization,person]
  max_gleanings: 1

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
"""


def _corpus_text(paper: dict[str, Any]) -> str:
    """Concatenate page markdown into one corpus document, with light page markers."""
    parts: list[str] = []
    for p in paper.get("pages", []) or []:
        md = (p.get("markdown") or "").strip()
        if md:
            parts.append(f"[page {p.get('index', 0) + 1}]\n{md}")
    return "\n\n".join(parts)


def ensure_root(paper_id: str, paper: dict[str, Any]) -> Path:
    """Create/refresh the per-paper GraphRAG root: settings.yaml, prompts/, input corpus."""
    root = root_for(paper_id)
    (root / "input").mkdir(parents=True, exist_ok=True)
    (root / "prompts").mkdir(parents=True, exist_ok=True)

    (root / "settings.yaml").write_text(_settings_yaml(), encoding="utf-8")

    # Copy GraphRAG index/query prompts from the bundled template (only if missing,
    # so a user's local prompt tweaks survive a rebuild).
    tmpl = config.GRAPHRAG_TEMPLATE_DIR / "prompts"
    if tmpl.exists():
        for src in tmpl.glob("*.txt"):
            dst = root / "prompts" / src.name
            if not dst.exists():
                dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")

    (root / "input" / f"{paper_id}.txt").write_text(_corpus_text(paper), encoding="utf-8")
    return root


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def build(paper_id: str, paper: dict[str, Any]) -> None:
    """Scaffold + build the index in-process (blocking). Records status.json.

    Serialized per paper by a lock so a manual rebuild can't collide with the
    auto-build kicked off on paper load.
    """
    lock = _lock_for(paper_id)
    if not lock.acquire(blocking=False):
        print(f"[graphrag] build already in progress for {paper_id}", file=sys.stderr)
        return
    root = root_for(paper_id)
    try:
        _write_status(root, "building", "Scaffolding GraphRAG root…")
        ensure_root(paper_id, paper)
        _write_status(root, "building", "Building knowledge graph (entities, communities, reports)…")
        print(f"[graphrag] building index for {paper_id} …", file=sys.stderr)
        # Imported lazily so the heavy graphrag import only happens when we actually build.
        from graphrag_qa import build_index
        build_index(root)
        _engines.pop(paper_id, None)  # force re-load of the fresh index on next query
        _write_status(root, "ready", "")
        print(f"[graphrag] index ready for {paper_id}", file=sys.stderr)
    except Exception as e:  # noqa: BLE001 — surface a clear, recoverable failure
        _write_status(root, "failed", f"{type(e).__name__}: {e}")
        print(f"[graphrag] build FAILED for {paper_id}: {e}", file=sys.stderr)
    finally:
        lock.release()


def build_async(paper_id: str, paper: dict[str, Any], force: bool = False) -> bool:
    """Start a background build. Returns True if started.

    Auto-build (force=False) is skipped when an index already exists. A manual rebuild
    (force=True) proceeds even when healthy, but never collides with a running build.
    """
    if not force and health(paper_id):
        return False
    lock = _lock_for(paper_id)
    if lock.locked():
        return False
    t = threading.Thread(target=build, args=(paper_id, paper), daemon=True,
                         name=f"graphrag-build-{paper_id}")
    t.start()
    return True


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

def get_engine(paper_id: str):
    """Return a cached GraphRAGQA engine for the paper, or None if not built yet."""
    if not health(paper_id):
        return None
    eng = _engines.get(paper_id)
    if eng is None:
        from graphrag_qa import GraphRAGQA
        eng = GraphRAGQA(root=root_for(paper_id))
        _engines[paper_id] = eng
    return eng
